version: "3.8"
services:
  client:
    build: ./client
    container_name: clientapp_c
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
  server:
    build: ./server
    container_name: serverapp_c
    ports:
      - "4041:4041"
    volumes:
      - ./server:/app
      - ./app/node_modules